const TCG = 'Gerlafingen';
function isHomeMatch(m){return m.home.includes(TCG)||m.away.includes(TCG)}
function nextMatch(team){return team.matches.find(m=>m.result==='0:0')||team.matches[team.matches.length-1]}
function tcgRank(team){return team.ranking.find(r=>r.team.includes(TCG))}
function matchRow(m){return `<tr class="${isHomeMatch(m)?'home-match':''}"><td>${m.round}</td><td>${m.date}${m.time?' - '+m.time:''}</td><td>${m.home} - ${m.away}</td><td><strong>${m.result}</strong></td></tr>`}
function rankingRow(r){return `<tr class="${r.team.includes(TCG)?'home-match':''}"><td>${r.rank}</td><td>${r.team}</td><td>${r.points}</td><td>${r.sets}</td></tr>`}
function teamCard(team){const n=nextMatch(team);const rank=tcgRank(team);return `<article class="team-card"><p class="team-meta">${team.group}</p><h3>${team.name}</h3><p><strong>Nächstes TCG-Spiel:</strong><br>${n.home} - ${n.away}<br>${n.date}${n.time?' um '+n.time:''}</p><p><strong>Aktueller Rang TCG:</strong> ${rank?rank.rank:'-'}</p><a class="button primary" href="#${team.slug}">Details anzeigen</a></article>`}
function teamDetail(team){return `<article class="detail-card" id="${team.slug}"><div class="detail-header"><div><p class="team-meta">${team.group}</p><h2>${team.name}</h2><p>Captain: ${team.captain}</p></div><a class="screen-link" href="screen.html">Clubhaus-Screen öffnen</a></div><div class="tables"><div class="table-wrap"><h3>Spielplan & Resultate</h3><table><thead><tr><th>Runde</th><th>Datum</th><th>Begegnung</th><th>Resultat</th></tr></thead><tbody>${team.matches.map(matchRow).join('')}</tbody></table></div><div class="table-wrap"><h3>Rangliste</h3><table><thead><tr><th>Rang</th><th>Team</th><th>PT</th><th>Sätze</th></tr></thead><tbody>${team.ranking.map(rankingRow).join('')}</tbody></table></div></div></article>`}
fetch('data/interclub.json').then(r=>r.json()).then(data=>{document.getElementById('team-overview').innerHTML=data.teams.map(teamCard).join('');document.getElementById('team-details').innerHTML=data.teams.map(teamDetail).join('')}).catch(()=>{document.getElementById('team-overview').innerHTML='<p>Interclub-Daten konnten nicht geladen werden.</p>'});
